analysissrc := "../analysis/"
falasrc := "../fala/"

default:
        just --list

all: analysis tex

analysis:
        cd "../analysis/" && R CMD BATCH main.R
        cd "../analysis/" && R CMD BATCH glm.R

tex:
        cd {{falasrc}} && lualatex --interaction=batchmode --draftmode main.tex
        cd {{falasrc}} && biber --quiet main
        cd {{falasrc}} && lualatex --interaction=batchmode --draftmode main.tex
        cd {{falasrc}} && lualatex --interaction=batchmode main.tex

